name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: ESLint
      uses: hallee/eslint-action@master
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    
    - name: Prettier
      run: yarn lint:prettier

    - name: todo-actions
      if: github.event == 'push'
      uses: dtinth/todo-actions@v0.2.0
